### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by kajo404** [Rostlab/JS16_ProjectD_Group5#42]
@sacdallago Do you have any idea how we should handle the configuration? New users should need to use their own mongodb and twitter api configuration.

**Comment by sacdallago** [comment]
Yes, that's the idea, right? I know that @AlexMoroz has been able to do this for **C10**, your **E** representative should take care of this

**Comment by kajo404** [comment]
I guess I'll assign @jonny3576 to this then ;)

**Comment by AlexMoroz** [comment]
You won't have mongo db config, you use api.

**Comment by AlexMoroz** [comment]
It was decided on 17th. You will have api config.

**Comment by AlexMoroz** [comment]
Create config.js as in C10  https://github.com/Rostlab/JS16_ProjectC_Group10/blob/develop/mockup/js/config.js , and add there twitter config variables.

**Comment by kajo404** [comment]
Yes I know, but we use an additional mongoDB where we store raw tweet information, and for this database we need to provide configuration. We still use Project A's database to store our results with API.

**Comment by kajo404** [comment]
Currently we have all the configuration data in a[ json](https://github.com/Rostlab/JS16_ProjectD_Group5/blob/develop/cfg/configDUMMY.json) in the package, but I was wondering how you would configure this from "the outside", e.g. as a package user after you did `npm install`

**Comment by AlexMoroz** [comment]
And you want to to send this db in the package to the project F?

**Comment by sacdallago** [comment]
OMG this is becoming a major brainfart :D
You will be exposing certain functions via the package so that **F** or **A** can use them, but still your tool need to be separately run to generate data over time...? Is that how you are thinking to do this?

Or do you want to also expose as function the runner that stores the tweets over time?

**Comment by kajo404** [comment]
AAAALright I'll let's clear this brainfart mess up. 

As of right now our program collects the tweets and stores them in a cloud databse. I just implemented a function that this task is run every 10 minutes for a different character. This will run the twitter analysis for every character of the top 117 characters (by wiki pagerank) every day.
This can also be done manually, for example for new characters, that are not yet in the list. 
 We then use the sentiment analysis to generate daily scores and save them in A's database over API. We provide a set of function that redirects the requests to A's database and does some additional calculations to provide top3 top5 ... for F to use directly in the webpage. We came to this solution after discussions with F (offline) where they said that they just want to run a function and display the result

**Comment by sacdallago** [comment]
I see! As I feared, this is a very complicated setup :D

I have one thing still that is not clear to me! The job that runs every 10 minutes: is that packaged in the npm package or is that available _only_ if you clone the repo an `node app.js`?

**Comment by sacdallago** [comment]
P.S.: 10 minutes???? Please let the user decide the time intervals! :D

**Comment by kajo404** [comment]
Okay so, it is quite a complicated setup. I guess this is what you get when you start out with no idea what to do and just add things as you go along :D. 
The automated job is included in the package and I want to load the node from the index.js. So when the index.js is loaded the automation is started. 

The reason for the 10 minute time interval is the limitation of the [twitter API](https://dev.twitter.com/rest/public/rate-limiting) (~160 requests/15min) . 10 minutes still allows requests for all characters in the list in a single day. 

Lowering the value might trigger the rate limits and using a higher value will result in not up to date data for some characters.

If the user wants to run twitter API requests outside of the information the application already provides 2 functions to do just that.

**Comment by sacdallago** [comment]
I was not thinking < 10, I was rather thinking > 10 min :D :D :D
I know, I know.. #Life is complicated. I didn't know everything was gonna unfold like this either. But in the end you achieved quite something, don't you agree?

I think it shouldn't be too complicated to export the timeouted function to the package, giving the possibility to set the interval as parameter... But your **E** representative might help you with that.

**Comment by jcebel** [comment]
Ok so after I talked with @kajo404 we decided the following (I'm the representative who didn't show up the whole day by the way - sorry for that):
We will add an additional function via index.js in the npm-package where you can configurate which additional Database should be filled (Project F gets the access for our database offline) over time. There also starts the jonas's automation function, which will be changed slightly, but basically it will pull data from the twitter_rest_API in a certain interval, which the caller of the initalize-function specified at the beginning.

**Comment by kajo404** [comment]
To clarify : we don't provide a function in index.js to configure the
database. The configuration is done in the config.json that is loaded when
starting the module. In the index.js we provide functions to start and stop
the automation and to set the time interval for the twitter analysis.

Jonas Ebel notifications@github.com schrieb am Sa., 19. März 2016 22:47:

**Comment by jcebel** [comment]
Ok we need more clarification.. Let's talk tomorrow again

**Comment by sacdallago** [comment]
This problem has already been solved in other projects @jonny3576 , talk to some of your project-mates about how they addressed the issue

**Comment by kajo404** [comment]
@sacdallago 

>  #Life is complicated. I didn't know everything was gonna unfold like this either. But in the end you achieved quite something, don't you agree?

I agree, so far it's been quite the adventure. I like to think of it like this:
[It's something](http://i.imgur.com/PppdzrD.png)

**Comment by jcebel** [comment]
maybe this time the plan is solid...
We've now decided to export only ONE function with the npm-module. Let's call it init... This init-function get's all information as argument, which are needed to connect to the databases, it starts the automation-process by default and after that returns all functionality, which can be currently seen in [index.js](https://github.com/Rostlab/JS16_ProjectD_Group5/blob/develop/index.js), as an object.

Additional we will add two functions to the index.js for stoping and starting the automationprocess (You will be able to specify the timeperiod of the automation).
@sacdallago hope this is something.

**Comment by sacdallago** [comment]
This is very, very good!
Ideologically the perfect solution, respect!

**Comment by gyachdav** [comment]
Sorry for coming so late in the game here but I was busy skiing the last two days :p

Jonas I still don't get why you want to store tweets at all. 

My understanding from what you said is the following :
- Sample Twitter every 10 minutes
- Store tweets in a DB
- Run a daily analysis over the stored tweets
- Store pre calculated analysis in As DB for public consumption 
- Add some aggregate topX characters in As DB for public consumption. 

Is that correct?  

If so I seriously don't get why you're storing the tweets. Isnt your app goal to calculate changing sentiments? Why dont you do this calc whenever you sample Twitter every 10 mins? 
I would just get the tweets run the analysis and then post to A the analysis result e.g +10, -40 or whatever metric you currently use. 

All you really need to store is a vector that looks  something like that [-34, 67, -259, -2099...]. This is stored as partied the char data on A's DB 

Unless I'm not getting something central here , storing the tweets and then asynchronous lay running periodic analysis sounds like a redundant step and an overcomplication.

**Comment by sacdallago** [comment]
@gyachdav it is redundant. The reason for doing this is that in the long run, if someone downloads this package and wants historic data, they can go back more than the 7days limitation of twitter.

Am I correct?

**Comment by kajo404** [comment]
Hello Guy,

I hope you had fun on your skiing trip. Your understanding is mostly correct. I am also aware that the design of our application is far from perfect and subpar at best. We came to this design based on design decisions that seemed doable at the time due to our limited knowledge about node / javascript. Of course this changed over time and there are a lot of things I would do differently now. We started out as a team of 3 people with no knowledge about javascript and node. But lets get to the point. All your criticism is valid and the solution you suggested is very good and way better than what we provide.

The reasons behind storing tweets are that we can get arround the rate limit of the twitter API a little bit because we can accumulate data over time. This also allows us to go back more than two weeks in the future. Having the data on hand also allows us to add functions in the future that can analyse data from the past that would otherwise not be available. If I am completely honest I dont think that most of these arguments will apply in the future and the data will just sit there and go to waste but these were the reasons we had to take this approach. We discussed this approach several times in the past with @sacdallago and didn't make any big decisions without confirmation. All of our decisions were made to the best of our ability and knowledge.

What we store in A's database are the results of the sentiment analysis for a character for a single day. This includes the sum of positive and negative sentimentand the count of tweets (pos / neg / neutral). This allows further processing of the data in different ways, not only top or flop. We can also look at what character is most controversial(biggest span positive / negative sum). At the time we had to decide on how to store this data in A's database we were still unsure of how and what we want to do with this information so we thought it would be best to save the data in a flexible way. I realize that this was a mistake on our part and we propably should have planned ahead better.

My overall goal always was to have a working system when the deadline comes arround and to reach this goal we had make sacrifices regarding functionality. This is sad but the time schedule really didn't allow for us to implement all our ideas we had in the beginning. But thats the reality about software development and many lessons were learned here. 

Let's look at the options we have here now. We can continue to develop the application with the features and databases as it is now. I think that my team can handle this task and we will have a working application on April 3rd. The other option is to redesign our system and change functionality completely. With this approach comes the uncertainty of having an unfinished system in the end. I am not sure that the team and I are capable of this task. 

This got really long really fast, sorry about that. Can I hand this in as a project report? :D 
I truly do realize that this application looks shitty in many ways to someone with a lot of experience. But it is my shit :) and @vanp33 's shit and @Logarythms 's shit :))) so please forgive me if I got a little to emotional about it.

**Comment by sacdallago** [comment]
Don't worry @kajo404 go on with what you had in mind. Let's get to a version 0.1 and deploy that. We can improve and work in less stressful conditions later on ;) after all, this project is still gonna be around after April 3rd and you are more then welcome to work on it ;) ;)

**Comment by gyachdav** [comment]
Hey Jonas,

Please do not be discouraged! You guys did an amazing work over the past three weeks and have probably learned a lot in the process. Even if you think you didn't get it completely right it doesn't mean hope is lost.  I for one absolutely love the idea of using aggregated data to calculate a controversial character measure. I already saw in the F issues that they plan on having this appear in the topX list view. 

Keep in mind that first version is always considered prototype so as long as the thing satisfies its base requirement (and functions) then all is good. Improvements are for 2.0. 

As Chris suggested let's have the app ready for delivery on the deadline and worry about optimization later on. 

Oh and Garmisch was fucking awesome :D
